processors_to_run: all
workspace_dir: ???
language_id: ???
resampled_audio_dir: ???
output_manifest_file: ???
chunksize: ???
in_memory_chunksize: ???
start: ???
end: ???

processors:
  - _target_: sdp.processors.CreateInitialManifestVoxpopuliUnlabelled
    raw_data_dir: ${workspace_dir}
    language_id: ${language_id}
    resampled_audio_dir: ${resampled_audio_dir}
    output_manifest_file: ${output_manifest_file}
    chunksize: ${chunksize}
    in_memory_chunksize: ${in_memory_chunksize}
    start: ${start}
    end: ${end}
    max_workers: -1
    delete_raw_file: False

